### ISSUE TITLE
Clean_GTFS not loading on appdaemon

### ISSUE THREAD

**Issue by diuna2000** [simonhq/Clean-GTFS#1]
Hi i have problem with appdaemon and Clean-GTFS appdaemon not loading bacause of missing globals:

`2020-10-14 12:03:55.933589 WARNING gtfs_cleanup: ------------------------------------------------------------
2020-10-14 12:03:55.937056 WARNING gtfs_cleanup: Unexpected error initializing app: gtfs_cleanup:
2020-10-14 12:03:55.940676 WARNING gtfs_cleanup: ------------------------------------------------------------
2020-10-14 12:03:55.945935 WARNING gtfs_cleanup: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 907, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 280, in init_object
    modname = await utils.run_in_executor(self, __import__, app_args["module"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 290, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/Clean-GTFS/cleangtfs.py", line 50, in <module>
    import globals
ModuleNotFoundError: No module named 'globals'

2020-10-14 12:03:55.948866 WARNING gtfs_cleanup: ------------------------------------------------------------
2020-10-14 12:03:55.952069 WARNING AppDaemon: Logged an error to /config/appdaemon/logs/appdaemon.log
2020-10-14 12:03:55.956720 WARNING AppDaemon: Unable to find module gtfs_cleanup - initialize() skipped
`
my config:`
gtfs_cleanup:
  module: cleangtfs
  class: Clean_GTFS
  GTFS_DB: "Bus_Éireann.sqlite"
  MY_STOPS: "8380B2433701,8370B2414801"
  GTFS_FLAG: "input_boolean.clean_gtfs"
  global_dependencies:
    - globals
    - secrets`
i using Home Assistant 0.116.2 any help would be appreciated.
Marcin

**Comment by simonhq** [comment]
Hi Marcin,

I have just removed the requirement for globals, let me know if you have any other issiues.

Simon.

**Comment by diuna2000** [comment]
Hi Simon
 Now working fine thanks for your tool.
Marcin
